# Custom images with CUDA toolkit installed
# See vm_images/ for instructions for building the images
images:
  linux-amd64:
    platform: "linux"
    arch: "x64"
    owner: "492475357299"  # XGBooost CI
    name: "xgboost-ci-runs-on-linux-amd64-*"
  new-linux-amd64:
    platform: "linux"
    arch: "x64"
    owner: "492475357299"  # XGBooost CI
    name: "new-xgboost-ci-runs-on-linux-amd64-*"

runners:
  new-linux-amd64-cpu:
    cpu: 16
    family: ["c7i-flex", "c7i", "c7a", "c5", "c5a"]
    image: new-linux-amd64
  linux-arm64-cpu:
    cpu: 16
    family: ["c6g", "c7g"]
    image: ubuntu24-full-arm64
