FROM quay.io/pypa/manylinux2014_x86_64

SHELL ["/bin/bash", "-c"]

ENV GOSU_VERSION=1.10

COPY scripts/install_gosu.sh /scripts/

RUN yum update -y && yum install -y java-1.8.0-openjdk-devel

# Install lightweight sudo (not bound to TTY)
RUN sh /scripts/install_gosu.sh

# Default entry-point to use if running locally
# It will preserve attributes of created files
COPY entrypoint.sh /scripts/

WORKDIR /workspace
ENTRYPOINT ["/scripts/entrypoint.sh"]
