name: update-sccache

on:
  workflow_dispatch:
  schedule:
    - cron: "0 20 * * 1"  # Run once weekly

permissions:
  pull-requests: write
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  update-sccache:
    name: Check latest sccache
    uses: ./.github/workflows/update_dependency.yml
    with:
      update-script: actions/update_sccache.sh
      add-paths: |
        actions/sccache/action.yml
      branch: create-pull-request/update-sccache
      title: "[CI] Update sccache to latest RAPIDS release"
      commit-message: "[CI] Update sccache to latest RAPIDS release"
    secrets: inherit
