name: update-rapids

on:
  workflow_dispatch:
  schedule:
    - cron: "0 20 * * 1"  # Run once weekly

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  update-rapids:
    name: Check latest RAPIDS
    uses: ./.github/workflows/update_dependency.yml
    with:
      update-script: containers/update_rapids.sh
      add-paths: |
        containers
      branch: create-pull-request/update-rapids
      title: "[CI] Update RAPIDS to latest stable"
      commit-message: "[CI] Update RAPIDS to latest stable"
      checkout-submodules: true
    secrets: inherit
